apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - coredns
  - cilium
  - http-proxy
  - longhorn
  - 1password
  - cert-manager
  - external-dns
  - traefik
  - garage
  - kanidm
