apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: kanidm
  namespace: kanidm
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`idm.yadunut.dev`)
      services:
        - name: kanidm
          port: https
  tls:
    passthrough: true
