apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  - backup.yaml
  - oauth2-proxy-onepassworditem.yaml
  - oauth2-proxy-helmrelease.yaml
  - certificate.yaml
  - middleware.yaml
  - ingressroute.yaml
