apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepo.yaml
  - onepassworditem.yaml
  - serviceaccount.yaml
  - certificate.yaml
  - helmrelease.yaml
