apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: garage-web
  namespace: garage
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`[a-z0-9-]+\.web\.garage\.yadunut\.dev`)
      kind: Rule
      services:
        - name: garage-web
          port: 3902
  tls:
    secretName: garage-web-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: garage-s3
  namespace: garage
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`s3.garage.yadunut.dev`) || HostRegexp(`[a-z0-9-]+\.s3\.garage\.yadunut\.dev`)
      kind: Rule
      services:
        - name: garage-s3
          port: 3900
  tls:
    secretName: garage-s3-tls
