apiVersion: v1
kind: Service
metadata:
  name: garage-web
  namespace: garage
spec:
  ports:
    - name: http
      port: 3902
      targetPort: 3902
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: garage-web-1
  namespace: garage
  labels:
    kubernetes.io/service-name: garage-web
addressType: IPv6
endpoints:
  - addresses:
      - "fd5d:644d:2e43:8ad9:ec99:9395:68d4:8771"
    conditions:
      ready: true
ports:
  - name: http
    port: 3902
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: garage-s3
  namespace: garage
spec:
  ports:
    - name: http
      port: 3900
      targetPort: 3900
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: garage-s3-1
  namespace: garage
  labels:
    kubernetes.io/service-name: garage-s3
addressType: IPv6
endpoints:
  - addresses:
      - "fd5d:644d:2e43:8ad9:ec99:9395:68d4:8771"
    conditions:
      ready: true
ports:
  - name: http
    port: 3900
    protocol: TCP
